version: "3.9"

services:
  api:
    build: .
    container_name: metadata_api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=metadata_db
      - LOG_LEVEL=INFO

  mongo:
    image: mongo:6
    container_name: metadata_mongo
    ports:
      - "27017:27017"
